package com.example.autorizame_api.service.impl;

import java.util.List;

import org.springframework.stereotype.Service;

import com.example.autorizame_api.model.Empresa;
import com.example.autorizame_api.repository.EmpresaRepository;
import com.example.autorizame_api.service.EmpresaService;
import com.example.autorizame_api.exception.RecursoNoEncontradoException;

/**
 * Implementación del servicio de Empresas usando JPA Repository.
 */
@Service
public class EmpresaServiceImpl implements EmpresaService {

    private final EmpresaRepository empresaRepository;

    public EmpresaServiceImpl(EmpresaRepository empresaRepository) {
        this.empresaRepository = empresaRepository;
    }

    @Override
    public List<Empresa> findAll() {
        return empresaRepository.findAll();
    }

    @Override
    public Empresa findById(Long id) {
        return empresaRepository.findById(id)
                .orElseThrow(() -> new RecursoNoEncontradoException("Empresa con id " + id + " no encontrado"));
    }

    @Override
    public Empresa create(Empresa empresa) {
        // ID is generated by DB
        return empresaRepository.save(empresa);
    }

    @Override
    public Empresa update(Long id, Empresa empresa) {
        Empresa existente = findById(id);

        existente.setNombre(empresa.getNombre());
        existente.setCif(empresa.getCif());
        existente.setEmail(empresa.getEmail());
        existente.setDireccion(empresa.getDireccion());
        existente.setTelefono(empresa.getTelefono());

        return empresaRepository.save(existente);
    }

    @Override
    public void delete(Long id) {
        Empresa existente = findById(id);
        empresaRepository.delete(existente);
    }
}
